set (WEBRTC_LIBRARIES "${CMAKE_CURRENT_LIST_DIR}/lib/libwebrtc.a;SM;ICE;X11;Xext;dl;rt")
set (WEBRTC_INCLUDE_DIRECTORIES "${CMAKE_CURRENT_LIST_DIR}/include")
set (WEBRTC_COMPILE_DEFINITIONS "-DWEBRTC_POSIX")
